version: '3.8'

services:
  db:
    image: postgres:15
    container_name: shop_db
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: shop_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: shop_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: shop_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-here
      - NAME_DB=shop_db
      - USER_DB=shop_user
      - PASSWORD_DB=shop_password
      - HOST_DB=db
      - PORT_DB=5432
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

volumes:
  postgres_data: